name: Build and Release

on: push

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build app
      run: make build && make modify_plist

    - name: Create ZIP archive
      run: zip -r SlicerSelector.app.zip SlicerSelector.app

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./SlicerSelector.app.zip

    - name: Get SHA256
      id: shasum
      run: echo "sha=$(shasum -a 256 SlicerSelector.app.zip | awk '{print $1}')" >> $GITHUB_OUTPUT

    - name: Checkout homebrew-SlicerSelector
      uses: actions/checkout@v3
      with:
        repository: spuder/homebrew-SlicerSelector
        path: homebrew-SlicerSelector
        token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

    - name: Update Cask
      run: |
        version=$(echo ${{ github.ref }} | sed 's/^refs\/tags\/v//')
        cd homebrew-SlicerSelector
        sed -i '' 's/version ".*"/version "'$version'"/' Casks/slicer-selector.rb
        sed -i '' 's/sha256 ".*"/sha256 "${{ steps.shasum.outputs.sha }}"/' Casks/slicer-selector.rb        git config user.name github-actions
        git config user.email github-actions@github.com
        git add Casks/slicer-selector.rb
        git commit -m "Update cask to version $version"
        git push
      if: startsWith(github.ref, 'refs/tags/')
